spring:
  mail:
    host: smtp.gmail.com
    port: 587
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  queueName: mail-queue
  mail:
    email: pgsfacebaak@gmail.com
    username: pgsfacebaak@gmail.com
    password: Facebook123.
    smtp:
      host: smtp.gmail.com
      port: 587
      auth: true
      starttls:
        enable: true
logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      pgs: DEBUG



