zuul:
  routes:
    auth:
      sensitiveHeaders:
      path: /auth/**
      url: http://localhost:5000/
    post:
      sensitiveHeaders:
      path: /post/**
      url: http://localhost:5001/
    event:
      sensitiveHeaders:
      path: /event/**
      url: http://localhost:5003/
    news:
      sensitiveHeaders:
      path: /news/**
      url: http://localhost:5004/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
