package com.pgs.news.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.ion.Timestamp;


@DynamoDBTable(tableName = "News")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class News implements Comparable<News> {


    private String id;
    private Long userId;
    private String title;
    private String content;
    private String createDate;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "UserId")
    public Long getUserId() {
        return userId;
    }

    @DynamoDBAttribute(attributeName = "Title")
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute(attributeName = "Content")
    public String getContent() {
        return content;
    }

    @DynamoDBAttribute(attributeName = "CreateDate")
    public String getCreateDate() {
        return createDate;
    }

    @Override
    public int compareTo(News o) {
        return Timestamp.valueOf(this.getCreateDate()).compareTo(Timestamp.valueOf(o.getCreateDate()));
    }
}
